### ISSUE TITLE
Error: apiKey value must be defined!

### ISSUE THREAD

**Issue by WillSquire** [orliesaurus/nodemailer-mailgun-transport#100]
This isn't working at all for me. When `apiKey` is set it still throws `Error: apiKey value must be defined!` from the `mailgun-js` dependency.

```ts
MailGunTransport({
  auth: {
    apiKey: configService.emailApiKey, // tried hard coding this, the value is definitely set
    domain: configService.emailDomain,
  },
  host: 'api.eu.mailgun.net',
}),
```

Versions:
"nodemailer": "^6.4.16",
"nodemailer-mailgun-transport": "^2.0.1",

**Comment by orliesaurus** [comment]
looks like you have a spelling error on the key name. Compare to this:

``` {
  auth: {
    api_key: 'key-1234123412341234',
    domain: 'one of your domain names listed at your https://mailgun.com/app/domains'
  },
  host: 'api.eu.mailgun.net'
}
```

**Comment by orliesaurus** [comment]
@WillSquire can you let me know?

**Comment by zgid123** [comment]
@WillSquire if you use with typescript, ignore the `apiKey` right now. Because my PR is merged but still not released yet

**Comment by WillSquire** [comment]
Apologies for not getting back. It is indeed the Typescript definition

**Comment by zgid123** [comment]
yup, I created that option after this PR #98 was merged, but the @types already released but the version of this package did not

**Comment by orliesaurus** [comment]
> yup, I created that option after this PR #98 was merged, but the @types already released but the version of this package did not

Did I forget to npm publish your version?

**Comment by zgid123** [comment]
Yes. I just reinstalled this package again and no new version. Checked the code in node_modules, the code does not contain my change

**Comment by orliesaurus** [comment]
> Yes. I just reinstalled this package again and no new version. Checked the code in node_modules, the code does not contain my change

Alright gonna fix it today! Thank you for reminding me I must ve forgotten woops!

**Comment by orliesaurus** [comment]
abrakadabra - pushed! Thanks @zgid123

**Comment by zgid123** [comment]
thank you, just tested and it worked with `apiKey`

**Comment by orliesaurus** [comment]
Perfect closing

**Comment by christopherreay** [comment]
I think maybe the documentation for this says the api key should be in the key "key"
