### ISSUE TITLE
high severity vulnerability in netmask plugin

### ISSUE THREAD

**Issue by zhyrin** [orliesaurus/nodemailer-mailgun-transport#103]
1. What kind of issue are you reporting?
- A bug in a plugin of nodemailer-mailgun-transport ^2.0.2 (netmask plugin)
- High severity vulnerability

2. State your problem here:
Run "npm audit" or "npm install" with nodemailer-mailgun-transport ^2.0.2
gives me: 
  "netmask npm package vulnerable to octal input data"
  "patched in >=2.0.1"

Netmask is used by up to 300k live projects. Vulnerability reported on about two days ago.

**Comment by orliesaurus** [comment]
Hey, I tried to patch the `package-lock.json` to use a NON-VULNERABLE version of netmask - I think it worked? Let me know what you're seeing now :)

**Comment by anachronic** [comment]
Looks fixed to me in a clean checkout + `npm install`

I'm still seeing it through `yarn audit`, though, I suspect it hasn't been published

**Comment by orliesaurus** [comment]
@anachronic I published in npm as `2.0.3` - https://www.npmjs.com/package/nodemailer-mailgun-transport

**Comment by rfox12** [comment]
This issue persists.  Please see https://github.com/mailgun/mailgun-js-boland/issues/269 for a hint on how to fix

**Comment by rfox12** [comment]
Somewhat disturbing discovery... apparently nodemailer-mailgun-transport has been using a now non-official mailgun library?  Is this an easy swap to the "official" version?  Seems like the proper dependency should be "mailgun.js" and then that will alleviate the security vulnerability (and hopefully help for future issues).  Discussion here: https://github.com/mailgun/mailgun-js/issues/122

**Comment by zhyrin** [comment]
Yeah just change the dependency and rewrite the code bit of code that are used for the official library.
official plugin: https://www.npmjs.com/package/mailgun.js
deprecated plugin: https://www.npmjs.com/package/mailgun-js (its referenced in mailgun docs, hence the confusion)

official uses '...require=('mailgun.js) as opposed to ...require('mailgun-js')

Tired, but hope it was a tldr

**Comment by orliesaurus** [comment]
@zhyrin  guess someone is gonna have to do some research to see how much code rewrite is needed

**Comment by zhyrin** [comment]
not interested

**Comment by anachronic** [comment]
> @zhyrin guess someone is gonna have to do some research to see how much code rewrite is needed

Is #104 not a fix for this?

**Comment by orliesaurus** [comment]
> not interested

great! at least you're honest about how you like open source

**Comment by orliesaurus** [comment]
> Is #104 not a fix for this?
let me take a look

**Comment by omerlh** [comment]
Look like the latest version of mail gun is still vulnerable? https://snyk.io/advisor/npm-package/mailgun-js

**Comment by orliesaurus** [comment]
@omerlh We've upgraded to the other one - that one is deprecated

**Comment by omerlh** [comment]
Which one? I can see the latest version is still vulnerable: https://snyk.io/advisor/npm-package/nodemailer-mailgun-transport

**Comment by anachronic** [comment]
I believe this is solved in master (see #104), however, 2.0.3 (last version published) seems to point to the last commit before the fix.

Although I'm not sure, maybe publishing a new version solves this?

**Comment by shawncarr** [comment]
@orliesaurus can we get a new release based on @anachronic's point?

**Comment by orliesaurus** [comment]
Yeah I definitely need to push the update that is in master! Thanks y'all!

**Comment by axelauvinen** [comment]
Any timeline on this version bump? Should this ticket be closed before the latest version is updated to master?
