### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by yamila-fraiman** [orliesaurus/nodemailer-mailgun-transport#108]
Hello, sometimes (I can't reproduce) I'm getting this error message in production "SyntaxError: Unexpected end of JSON input" at node_modules/mailgun.js/dist/mailgun.js:2:40191. When I use smtp everything is working ok.

Any idea?

**Comment by orliesaurus** [comment]
Looks like it's an issue with mailgun.js
