### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by 0x001122** [orliesaurus/nodemailer-mailgun-transport#117]
Hello 👋

Would it please be possible to push a new version to npm? I'm especially interested in the new `timeout` option that has been introduced in https://github.com/orliesaurus/nodemailer-mailgun-transport/pull/111.

**Comment by orliesaurus** [comment]
Sounds gucci

**Comment by orliesaurus** [comment]
my pleasure @0x001122 <3
