### ISSUE TITLE
Why use this package?

### ISSUE THREAD

**Issue by Fonger** [orliesaurus/nodemailer-mailgun-transport#12]
I found the following code just working for me.
Any reason to use this package?

```js
var transporter = nodemailer.createTransport({
	service: 'Mailgun',
	auth: {
		user: 'postmaster@mailgun.domain.com',
		pass: 'password'
	}
});
```

**Comment by orliesaurus** [comment]
This allows you to send emails through the web-api which can circumnavigate SMTP connections issues. You can use the smtp transport the way you showed, I am not forcing anyone to use the module..lol
