### ISSUE TITLE
Support for Reply-to missing

### ISSUE THREAD

**Issue by dimitarkolev** [orliesaurus/nodemailer-mailgun-transport#13]
Right now this transport is missing support for replyTo when sending messages.

**Comment by orliesaurus** [comment]
Hey, you're right! I'll have to add it eventually. Please feel free to contribute to the project :)

**Comment by amingilani** [comment]
I'd add this myself, if I knew how to! Please @orliesaurus? You'd be an amazing person!

**Comment by orliesaurus** [comment]
wish granted @amingilani @dimitarkolev check the README.md
