### ISSUE TITLE
Attachments?

### ISSUE THREAD

**Issue by dreki** [orliesaurus/nodemailer-mailgun-transport#14]
Are attachments not supported? I haven't been able to get them to work. The same code using the sendgrid transport works fine.

**Comment by orliesaurus** [comment]
they are :+1: just not documented!

**Comment by akshitgoel** [comment]
Could you please tell how to add attachment as I haven't been able to get them to work as well...

**Comment by orliesaurus** [comment]
under html, text or whatever add
```
attachment: "the/path/of/your.file"
```

**Comment by wmcmurray** [comment]
Note that in nodemailer, the `attachement` key is in the plural form (`attachments` https://github.com/andris9/Nodemailer#attachments) so if you pass an object with the same format as nodemailer, it won't be seen by this transport. [This pull request](https://github.com/orliesaurus/nodemailer-mailgun-transport/pull/15) intend to fix this.

**Comment by orliesaurus** [comment]
awesome job :)
