### ISSUE TITLE
Mailgun error when template isset

### ISSUE THREAD

**Issue by ernie58** [orliesaurus/nodemailer-mailgun-transport#20]
I'm using `nodemailer-mailgun-transport` with loopback js.
When I try to send an e-mail I get the following error back from Mailgun

    { [Error: Sorry: template parameter is not supported yet. Check back soon!] statusCode: 400 }

Apparently, loopback js has a `data.template` property on the `mail` object provided as the first argument in the `send` method. They use it to generate the html provided in `data.html`, further it has no importance anymore.

When I put this in the send-method, everything works:

    delete mail.data.template;

Could you add this line, just like you delete the `mail.data.headers` ?

Thx

**Comment by orliesaurus** [comment]
Hi Ernie,
What exactly are you proposing ? I am not understanding it clearly.
thanks

**Comment by ernie58** [comment]
I'll submit a pull request

**Comment by ernie58** [comment]
Seems this was fixed in #17 , sorry!
