### ISSUE TITLE
from should support structure, not only string

### ISSUE THREAD

**Issue by mogadanez** [orliesaurus/nodemailer-mailgun-transport#21]
```
 from: {
                    name: "",
                    address:""
                },
```

now its failed with `Error: Invalid parameter type. from must be of type: string.`

**Comment by orliesaurus** [comment]
Hello @mogadanez - thanks for opening the issue.
Would you like to open a pull request and propose a fix to this issue?

**Comment by orliesaurus** [comment]
@mogadanez it's almost been a year, can I close this?

**Comment by ADumaine** [comment]
Sent a pull request to support address objects.

**Comment by ADumaine** [comment]
Reworked address objects after being reverted and yesterday sent new pull request that includes tests.

**Comment by pi-kei** [comment]
Done in #54

**Comment by nicklasfrahm** [comment]
@orliesaurus This seems to be fixed and could potentially be closed.

**Comment by framp** [comment]
master is handling it /cc @orliesaurus
