### ISSUE TITLE
in sendMail callback info (second param) always undefined?

### ISSUE THREAD

**Issue by iggyZiggy** [orliesaurus/nodemailer-mailgun-transport#25]
code:

```
tmg.sendMail(options, function(error, info){
  if(error)console.log("mailgun error:", error)
  else console.log("sent mail info:", info);
}
```

output:

```
sent mail info: undefined
```

**Comment by orliesaurus** [comment]
Thanks for opening the issue @iggyZiggy - will probably be fixed in the next update :) 👍

**Comment by itsyogesh** [comment]
For someone who is still looking into this, the second param `info` does return some mailgun specific data. You can look into you mailgun configuration for the errors. If the mailgun auth is not setup correctly it would fail silently. For example, and I did this, setting up an incorrect `DOMAIN NAME`, or the entire `base url` as domain name in auth would fail silently. Learned this the hard way.

Cheers
