### ISSUE TITLE
error callback param is undefined instead of null

### ISSUE THREAD

**Issue by JoshWillik** [orliesaurus/nodemailer-mailgun-transport#27]
I'm not sure if this is a problem with this library or the underlying mailgun library, but it could be fixed by this library regardless.

When an email successfully sends, the error callback param is `undefined`.

This goes against the nodejs callback pattern of using `null` in the absence of an error. [source](http://blog.gvm-it.eu/post/22040726249/callback-conventions-in-nodejs-how-and-why)

Could you change the library to return a `null` error on success?
Alternately, would you accept a PR that did that?

**Comment by orliesaurus** [comment]
Hi @JoshWillik , that's a valid point - Yes please send PR in - I'll merge it straight in
