### ISSUE TITLE
How to disable consolidate?

### ISSUE THREAD

**Issue by martinhbramwell** [orliesaurus/nodemailer-mailgun-transport#39]
Hi,

I don't need templates. Is there a way to disable `consolidate`?  Perhaps, a `lite` version?

I use `Meteor`.  It aggressively searches for, and warns of absence of, `npm` packages that should have been installed, so I end up with >35 lines of complaints in my server log.

**Comment by orliesaurus** [comment]
@stevepaulo can reply to this one

**Comment by martinhbramwell** [comment]
My, (happily working ! ), code looks like this : 



    var nodemailer = require('nodemailer');
    var mg = require('nodemailer-mailgun-transport');

    var auth = {
      auth: {
        api_key: Meteor.settings.MAILGUN_KEY,
        domain: Meteor.settings.MAILGUN_DOMAIN
      }
    };

    let mailer = nodemailer.createTransport(mg(auth));

My package.json contains : 

    "dependencies": {
           : 
      "nodemailer-mailgun-transport": "^1.2.0",
           : 

Where would I *"not pass the consolidate argument"* while Meteor starts-up my application?

**Comment by stevepaulo** [comment]
I guess I'm a little at a loss here. I'm not familiar with Meteor. Why does it matter that this module includes Consolidate? Why can't you just not use the `template` key?

**Comment by martinhbramwell** [comment]
Yes.  I am making a mountain out of a mole hill.  I experience **zero** run-time effects.

But, let me clarify, please.

I'm working on a "kickstarter" app.  Kickstarters are typically used by novices or people out to evaluate a technology, so "first impressions" matter a lot.  Grubby execution logs leave a bad impression.

Right now, `nodemailer-mailgun-transport` is making my whole app look sloppy, for no real reason : 

    you@kik:~/projects/meteor-mantra-kickstarter$ meteor --settings=setting.json
    [[[[[ ~/projects/meteor-mantra-kickstarter ]]]]]          

    => Started proxy.                             
    => Started MongoDB.                           
                                                  
    Unable to resolve some modules:

      "tinyliquid" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "./lib-cov/jade" in /home/you/projects/meteor-mantra-kickstarter/node_modules/jade/index.js (os.linux.x86_64)
      "sass" in /home/you/projects/meteor-mantra-kickstarter/node_modules/jade/lib/filters.js (os.linux.x86_64)
      "stylus" in /home/you/projects/meteor-mantra-kickstarter/node_modules/jade/lib/filters.js (os.linux.x86_64)
      "less" in /home/you/projects/meteor-mantra-kickstarter/node_modules/jade/lib/filters.js (os.linux.x86_64)
      "markdown" in /home/you/projects/meteor-mantra-kickstarter/node_modules/jade/lib/filters.js (os.linux.x86_64)
      "discount" in /home/you/projects/meteor-mantra-kickstarter/node_modules/jade/lib/filters.js (os.linux.x86_64)
      "markdown-js" in /home/you/projects/meteor-mantra-kickstarter/node_modules/jade/lib/filters.js (os.linux.x86_64)
      "marked" in /home/you/projects/meteor-mantra-kickstarter/node_modules/jade/lib/filters.js (os.linux.x86_64)
      "coffee-script" in /home/you/projects/meteor-mantra-kickstarter/node_modules/jade/lib/filters.js (os.linux.x86_64)
      "then-jade" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "dust" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "dustjs-helpers" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "dustjs-linkedin" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "swig" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "atpl" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "liquor" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "twig" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "ejs" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "eco" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "jazz" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "jqtpl" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "hamljs" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "hamlet" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "whiskers" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "haml-coffee" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "hogan.js" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "templayed" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "handlebars" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "pug" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "then-pug" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "qejs" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "walrus" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "mustache" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "just" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "ect" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "mote" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "toffee" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "dot" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "ractive" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "nunjucks" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "htmling" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "react-tools" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "vash" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
      "slm" in /home/you/projects/meteor-mantra-kickstarter/node_modules/consolidate/lib/consolidate.js (os.linux.x86_64)
                                                  
    If you notice problems related to these missing modules, consider running:
                                                  
      meteor npm install --save tinyliquid sass stylus less markdown discount markdown-js marked coffee-script then-jade dust dustjs-helpers dustjs-linkedin swig atpl liquor twig ejs eco jazz jqtpl hamljs hamlet whiskers haml-coffee hogan.js templayed handlebars pug then-pug qejs walrus mustache just ect mote toffee dot ractive nunjucks htmling react-tools vash slm


If you're evaluating a new tool and that's the first thing you see, how much confidence do you have that **anything** else is done well?

**Comment by orliesaurus** [comment]
@martinhbramwell I'm not sure which part of "do not specify a consolidate template" is not clear?

**Comment by stevepaulo** [comment]
I don't think he is, @orliesaurus. I think this has to do with how Meteor loads NPM modules and deals with (or doesn't deal with) nested dependencies. 

The fact is, @martinhbramwell, this is a Node module that works without causing logspam in Node. I know I don't have the time or the domain knowledge to ensure this module is compatible with Meteor. Perhaps you could fork the project and make a version that is?

**Comment by orliesaurus** [comment]
@martinhbramwell show us ur code to see how you're using the module

**Comment by martinhbramwell** [comment]
[where I use it](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/v0.2.1/server/methods/mail.js)

[where I specify it](https://github.com/warehouseman/meteor-mantra-kickstarter/blob/v0.2.1/package.json)

[where I workaround the problem](https://github.com/warehouseman/meteor-mantra-kickstarter/tree/v0.2.1/.workarounds)

Thank you for your patience.

This is a miniscule problem between `Meteor` and `Consolidate` that really doesn't concern you.
I should not have bothered you with it.

**Comment by orliesaurus** [comment]
Okay so let's close this issue then @martinhbramwell ?

**Comment by orliesaurus** [comment]
thank you :) 👍
