### ISSUE TITLE
Transport drops out Content-Disposition and Content-ID headers from attachments

### ISSUE THREAD

**Issue by elhigu** [orliesaurus/nodemailer-mailgun-transport#43]
I'm trying to send mail with embedded images through mailgun transport. I was expecting to see following headers in the received mail:

```
Content-Type: image/gif; name=timantti.gif
Content-ID: <timantti@superselfiestick.fi>
Content-Disposition: inline; filename=timantti.gif
Content-Transfer-Encoding: base64
```

but only 

```
Content-Disposition: attachment; filename="timantti.gif"
Content-Type: image/gif; name="timantti.gif"
Mime-Version: 1.0
Content-Transfer-Encoding: base64
```

were passed... 

Looks like many of the nodemailer options are just dropped here https://github.com/orliesaurus/nodemailer-mailgun-transport/blob/master/src/mailgun-transport.js#L83

**Comment by orliesaurus** [comment]
Would you like to send a pull request with that feature please?

**Comment by elhigu** [comment]
I just might if I find how to do it with mailgun APIs :) For fast fix I just changed our app to use smtp transport with mailgun smtp server to get mails going correctly.

**Comment by elhigu** [comment]
Yeah looks like it is enough to write nodemailer's `attachment.cid` attribute to mailguns `attachment.inline` (https://documentation.mailgun.com/user_manual.html#sending-via-api). I couldn't find if setting `Content-Disposition` value explicitly is possible at all.

**Comment by elhigu** [comment]
Looks like tests are never even running the code, which converts nodemailer attachment to mailgun one.. (I added debug prints to code, which were never executed). 

So fixing this will take some more tIme... If it is ok I'll add also code coverage for test run to see a bit easier which part were actually executed by tests.

**Comment by elhigu** [comment]
Aaand, yeah `mailgun-js` doesn't support setting inline attribute for attachment... so before this can be fixed `mailgun-js` issue https://github.com/bojand/mailgun-js/issues/103 must be resolved first.

**Comment by icetee** [comment]
Is it likely that is I cannot embed images in the mail? (Only attachment)

**Comment by orliesaurus** [comment]
Fixed ?

**Comment by elhigu** [comment]
@orliesaurus looks like it was implemented in by #45, as far as I can see implementation did seem correct. Pull request didn't have tests so it might work or might not.

**Comment by orliesaurus** [comment]
👍

**Comment by icetee** [comment]
Thanks!
