### ISSUE TITLE
Url not found on server when trying to send an email

### ISSUE THREAD

**Issue by luis-alvarez** [orliesaurus/nodemailer-mailgun-transport#5]
Hi,
I'm trying to use this node module, but when I try to send an e-mail I get:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.</p><p>If you entered the URL manually please check your spelling and try again.</p>
Will much appreciate your help. Thanks!

**Comment by androidfred** [comment]
@luis-alvarez 

```javascript
var auth = {
  auth: {
    api_key: 'key-1234123412341234'
    domain: 'one of your domain names listed at your mailgun.com/app/domains'
  }
};
```

**Comment by MetaMemoryT** [comment]
This should be added to README.md, would make usage more user friendly.

**Comment by luis-alvarez** [comment]
I actually opted to use mailgun smtp if it helps someone. Can't remember if @androidfred solution worked.

**Comment by MetaMemoryT** [comment]
It's working for me at the moment.

**Comment by orliesaurus** [comment]
I merged the change in the documentation, thanks :)
