### ISSUE TITLE
Seems Ignoring headers

### ISSUE THREAD

**Issue by iamchathu** [orliesaurus/nodemailer-mailgun-transport#50]
I tried to send email adding 

```js
headers: {
            "List-Unsubscribe": "<mailto:unsubscribe-new-arrivals@unsub.domain>, <http://unsub.domain/member/unsubscribe/?listname=name&email=>"
        },
```

But it didn't sent with email

**Comment by orliesaurus** [comment]
@iamchathu can you try:
```  'h:List-Unsubscribe': 'someemail@test.com' ```

**Comment by iamchathu** [comment]
@orliesaurus 

Did you mean this?

```js
headers: {
            'h:List-Unsubscribe': 'unsub@mydomain.tld'
        }
```

It didn't send the header still. I loaded original email and checked.

I found the documentation of nodemail regarding list options and tested it with below options but it also didn't work.

```js
list: {
            // List-Help: <mailto:admin@example.com?subject=help>
            help: 'admin@example.com?subject=help',
            // List-Unsubscribe: <http://example.com> (Comment)
            unsubscribe: {
                url: 'http://unsub.example.com/'
                    // comment: 'Comment'
            }
        }
```

**Comment by orliesaurus** [comment]
@iamchathu did you figure it out or do you still encounter difficulties with this feature?

**Comment by iamchathu** [comment]
@orliesaurus I still could get this sorted.

**Comment by orliesaurus** [comment]
could or couldnt ?

**Comment by iamchathu** [comment]
Sorry I couldn't

**Comment by marcosgouvea** [comment]
i need help on that too.

**Comment by orliesaurus** [comment]
`nodemailerMailgun.sendMail({
  from: 'myemail@example.com',
  to: 'recipient@domain.com',
  cc:'second@domain.com',
  bcc:'secretagent@company.gov',
  subject: 'Hey you, awesome!',
  'h:NAME-OF-YOUR-HEADER': 'SOME-HEADER-VALUE-123',
  html: '<b>HELLO WORLD</b>',
  text: 'HELLO'
}, function (err, info) {
  if (err) {
    console.log('Error: ' + err);
  }
  else {
    console.log('Response: ' + info);
  }
});`

**Comment by bajaga** [comment]
This is not working for sure, i tried everything with help and unsubscribe list headers but nothing. What would be the exact example of setting an unsubscribe header?
'h:List-Help': 'SOME-HEADER-VALUE-123' ??

**Comment by mariohmol** [comment]
Hi @bajaga did u figure it out?

**Comment by orliesaurus** [comment]
Try a similar approach to https://github.com/orliesaurus/nodemailer-mailgun-transport/issues/70#issuecomment-446847846
