### ISSUE TITLE
how to send mails to mailing list?

### ISSUE THREAD

**Issue by suriyaJaay** [orliesaurus/nodemailer-mailgun-transport#52]
hi,

pls someone tell me how to send mails to mailing list from my front end.?
am using mailgun api. node as backend. just simple html for front end that has some sender and receiver, body of the message field. i can able to send mail successfully. but i want to send mailing list which in mailgun account. what am trying to say is. i have  50+ contacts in mailgun account named as " my demo list"  i just want send mails to that list from my front end. 

kindly share snippets or example code/tutorial/video links/ guidance pls..

thanks in advance

**Comment by orliesaurus** [comment]
a mailing list has an address, simply email that address with the email you want them to receive
