### ISSUE TITLE
MailgunTransport.send() should not throw errs, but return them to the callback

### ISSUE THREAD

**Issue by texels** [orliesaurus/nodemailer-mailgun-transport#60]
The throw is currently causing my process to exit if I give it an invalid template file.

online ~62: if (err) throw err;
should instead be: 
if ( err ) { 
 return done( err ) // will cause the async series result callback to be invoked with err
}

and ~121: if ( err ) throw err
should instead be:
if ( err ) {
  callback( err )
}

**Comment by rolftimmermans** [comment]
Yeah this is a serious problem that crashes processes.

Is the fix as straightforward as described above?

**Comment by framp** [comment]
master is not throwing errors anymore /cc @orliesaurus
