### ISSUE TITLE
replyTo not working

### ISSUE THREAD

**Issue by e110c0** [orliesaurus/nodemailer-mailgun-transport#63]
I've seen #19 but it seems the current code brought this bug back. If I `'h:Reply-To'` field to the message configuration for nodemailer, all is fine. But this breaks with the normal configuration of nodemailer and it is not possible anymore to switch between nodemailer plugins.

**Comment by orliesaurus** [comment]
Accepting pull requests :)

**Comment by e110c0** [comment]
is there a chance to publish this as v1.3.6, I'd rather keep the official project in my code than my fork :)
