### ISSUE TITLE
How to set tags?

### ISSUE THREAD

**Issue by devotox** [orliesaurus/nodemailer-mailgun-transport#68]

**Comment by orliesaurus** [comment]
can you please describe what you're trying to achieve a little bit better by providing a description?

**Comment by rohit-smpx** [comment]
Hi, I have the same issue. This is what he is talking about : https://documentation.mailgun.com/en/latest/user_manual.html#tagging

**Comment by orliesaurus** [comment]
@rohit-smpx can u try to add:
`'o:tag':'test'`
in the object passed to sendMail?
If it works I will document it

**Comment by rohit-smpx** [comment]
It works 👍

**Comment by MichielDeMey** [comment]
Yep, I can confirm that this works. Might want to relabel this issue other than `invalid`?

**Comment by orliesaurus** [comment]
@MichielDeMey what do you suggest?

**Comment by MichielDeMey** [comment]
Something like `question`?
