### ISSUE TITLE
Multiple Tags

### ISSUE THREAD

**Issue by vinceprofeta** [orliesaurus/nodemailer-mailgun-transport#71]
There is currently no way to add multiple tags since you pass options to nodemailer as an object.

**Comment by rbadr** [comment]
Hello @vinceprofeta 👋  I know this is an old ticket, but I was wondering, did you find a solution for this ? 😅

**Comment by rbadr** [comment]
Hello @orliesaurus 👋 Do you know if it's possible ? Mailgun supports up to 3 tags per message
