### ISSUE TITLE
High severity vulnerability introduced via `mailgun-js@0.13.1`

### ISSUE THREAD

**Issue by adrukh** [orliesaurus/nodemailer-mailgun-transport#75]
Disclaimers:
1. I work for Snyk.
2. Snyk uses `nodemailer-mailgun-transport` in its backend.

There is a high severity vulnerability in `nodemailer-mailgun-transport`, introduced via ` mailgun-js@0.13.1 › proxy-agent@2.1.0 › http-proxy-agent@1.0.0`. See more details on the [test report](https://snyk.io/test/npm/nodemailer-mailgun-transport/1.3.6).

This can be remediated by upgrading the `mailgun-js` dependency version range from `^0.13.1` to `^0.17.0` or higher.

I'm more than willing to open the PR that does this, raising this issue first to get the maintainer's blessing.

**Comment by orliesaurus** [comment]
You have my Bllessing @adrukh.

**Comment by adrukh** [comment]
@snyk is all about giving developers a way to own the security of their applications :)

I'll refrain from using this issue as a ground for our marketing efforts, but will suggest to add a badge to your readme, letting your users know you care about security!

Something like this:

[![Known Vulnerabilities](https://snyk.io/test/github/orliesaurus/nodemailer-mailgun-transport/badge.svg)](https://snyk.io/test/github/orliesaurus/nodemailer-mailgun-transport)

**Comment by adrukh** [comment]
Closing with the release of v1.4.0, thanks for the quick turnaround! Our backend is already vuln-free :)
