### ISSUE TITLE
mailgun-js is no longer maintained

### ISSUE THREAD

**Issue by andyli** [orliesaurus/nodemailer-mailgun-transport#83]
According to the [mailgun-js README](https://github.com/bojand/mailgun-js#maintenance-notice):

> This library is no longer maintained. It was started over 6 years ago because we were Mailgun customers and needed a good Node.js client. Since then this module has become more popular then ever expected, and even official documentation references it. Likewise a lot has changed over the years. Due to various factors my employer nor I use Mailgun any more, and we have not for a couple of years now. I have attempted to maintain the library but over time that has proved to be increasingly more difficult as I do not use it and have no need for it. I have reached out to Mailgun to inquire if they would take over the module and repository but never received any meaningful response. I would be happy to add a well-intentioned contributor to maintain this; but I do not have the time, incentive, and plans to maintain this module any more.

Maybe you can take over the maintenance of mailgun-js, or migrate off it and use something else?

Edit:
There is [mailgun.js](https://www.npmjs.com/package/mailgun.js) that is maintained by mailgun itself.

**Comment by orliesaurus** [comment]
Uh-oh! That's a big problem in the open source community! Thanks for raising the point!

**Comment by framp** [comment]
Even the official SDK seems to be de-facto abandoned and mailgun-js works fine
https://github.com/mailgun/mailgun-js/issues/43

Eg: It's not clear from the docs whether official sdk supports attachments

Maybe we should just adopt mailgun-js

**Comment by jacobbogers** [comment]
Hi, I just noticed your email today, I use mail gun extensively, are you looking for a maintainer?

**Comment by rococosans** [comment]
The API appears to be slightly different between mailgun.js and mailgun-js. Curious to know where everyone stands on this?

**Comment by sk-** [comment]
According to https://github.com/highlycaffeinated/mailgun-js/issues/258, the repo is in the process of being migrated to mailgun org, so it does not seem to be unmaintained anymore.

**Comment by orliesaurus** [comment]
Good to know!~
