### ISSUE TITLE
Add support for custom message id

### ISSUE THREAD

**Issue by EmilienD** [orliesaurus/nodemailer-mailgun-transport#86]
According to [the last question in the FAQ](https://documentation.mailgun.com/en/latest/faqs.html#how-do-i-track-which-email-a-recipient-has-replied-to), Mailgun allows setting custom Message-Id, but it seems the transport doesn't allow this. I'm willing to do a PR if you think this is indeed a missing feature.

**Comment by orliesaurus** [comment]
Sure, please and thank you
