### ISSUE TITLE
[Get rid of / Patch] mailgun-js

### ISSUE THREAD

**Issue by peterpro** [orliesaurus/nodemailer-mailgun-transport#90]
It's outdated & referencing to broken dependencies (broken in Node >=10), see https://github.com/highlycaffeinated/mailgun-js/issues/246 with root problem in https://github.com/TooTallNate/node-agent-base/issues/35

I'm very grateful for your cool library, but I'm forced to used https://github.com/mailgun/mailgun-js. It's old as God himself, but not breaking my app :(

**Comment by vanntile** [comment]
I want to add a heads up to this issue. What would be the minimum necessary to patch this?

**Comment by bradenmacdonald** [comment]
https://www.npmjs.com/package/mailgun.js is the official replacement
